// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go

// Package mock_reminder is a generated GoMock package.
package mock_reminder

import (
	context "context"
	reflect "reflect"

	model "github.com/Pizhlo/bot-reminder-go-telegram/internal/bot/model"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockreminderEditor is a mock of reminderEditor interface.
type MockreminderEditor struct {
	ctrl     *gomock.Controller
	recorder *MockreminderEditorMockRecorder
}

// MockreminderEditorMockRecorder is the mock recorder for MockreminderEditor.
type MockreminderEditorMockRecorder struct {
	mock *MockreminderEditor
}

// NewMockreminderEditor creates a new mock instance.
func NewMockreminderEditor(ctrl *gomock.Controller) *MockreminderEditor {
	mock := &MockreminderEditor{ctrl: ctrl}
	mock.recorder = &MockreminderEditorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreminderEditor) EXPECT() *MockreminderEditorMockRecorder {
	return m.recorder
}

// DeleteAllByUserID mocks base method.
func (m *MockreminderEditor) DeleteAllByUserID(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllByUserID indicates an expected call of DeleteAllByUserID.
func (mr *MockreminderEditorMockRecorder) DeleteAllByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllByUserID", reflect.TypeOf((*MockreminderEditor)(nil).DeleteAllByUserID), ctx, userID)
}

// DeleteReminderByID mocks base method.
func (m *MockreminderEditor) DeleteReminderByID(ctx context.Context, userID int64, reminderID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReminderByID", ctx, userID, reminderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReminderByID indicates an expected call of DeleteReminderByID.
func (mr *MockreminderEditorMockRecorder) DeleteReminderByID(ctx, userID, reminderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReminderByID", reflect.TypeOf((*MockreminderEditor)(nil).DeleteReminderByID), ctx, userID, reminderID)
}

// GetAllByUserID mocks base method.
func (m *MockreminderEditor) GetAllByUserID(ctx context.Context, userID int64) ([]model.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByUserID", ctx, userID)
	ret0, _ := ret[0].([]model.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByUserID indicates an expected call of GetAllByUserID.
func (mr *MockreminderEditorMockRecorder) GetAllByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByUserID", reflect.TypeOf((*MockreminderEditor)(nil).GetAllByUserID), ctx, userID)
}

// GetAllJobs mocks base method.
func (m *MockreminderEditor) GetAllJobs(ctx context.Context, userID int64) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllJobs", ctx, userID)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllJobs indicates an expected call of GetAllJobs.
func (mr *MockreminderEditorMockRecorder) GetAllJobs(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllJobs", reflect.TypeOf((*MockreminderEditor)(nil).GetAllJobs), ctx, userID)
}

// GetJobID mocks base method.
func (m *MockreminderEditor) GetJobID(ctx context.Context, userID int64, reminderID int) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobID", ctx, userID, reminderID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobID indicates an expected call of GetJobID.
func (mr *MockreminderEditorMockRecorder) GetJobID(ctx, userID, reminderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobID", reflect.TypeOf((*MockreminderEditor)(nil).GetJobID), ctx, userID, reminderID)
}

// Save mocks base method.
func (m *MockreminderEditor) Save(ctx context.Context, reminder *model.Reminder) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, reminder)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockreminderEditorMockRecorder) Save(ctx, reminder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockreminderEditor)(nil).Save), ctx, reminder)
}

// SaveJob mocks base method.
func (m *MockreminderEditor) SaveJob(ctx context.Context, userID, reminderID int64, jobID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveJob", ctx, userID, reminderID, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveJob indicates an expected call of SaveJob.
func (mr *MockreminderEditorMockRecorder) SaveJob(ctx, userID, reminderID, jobID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveJob", reflect.TypeOf((*MockreminderEditor)(nil).SaveJob), ctx, userID, reminderID, jobID)
}
