name: go vet test

on:
  push:

jobs:
    audit:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2
    
        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: '1.23'
            
        - name: Verify dependencies
          run: go mod verify
    
        - name: Run go vet
          run: go vet ./...

        - name: Install staticcheck
          run: go install honnef.co/go/tools/cmd/staticcheck@latest

        - name: Run staticcheck
          run: staticcheck ./...